apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: cdc-webhook
  namespace: ceer-cdc
spec:
  gateway: kyma-system/kyma-gateway
  rules:
    - path: /*
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      noAuth: true
  hosts:
    - ceer-cdc-nag
  service:
    name: cdc-webhook
    port: 80
