apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: cdc-webhook
  namespace: ceer-cdc
  labels:
    app: cdc-webhook
spec:
  resourceConfiguration:
    function:
      profile: XS
  runtime: nodejs20
  env:
  - name: CDC_API_KEY
    valueFrom:
      secretKeyRef:
        key: CDC_API_KEY
        name: cdc-webhook-secret
  - name: CDC_KID
    valueFrom:
      secretKeyRef:
        key: CDC_KID
        name: cdc-webhook-secret
  - name: CDC_N_MODULUS
    valueFrom:
      secretKeyRef:
        key: CDC_N_MODULUS
        name: cdc-webhook-secret
  - name: CDC_E_EXPONENT
    valueFrom:
      secretKeyRef:
        key: CDC_E_EXPONENT
        name: cdc-webhook-secret
  source:
    inline:
      dependencies: |
        {
          "name": "cdc-webhook",
          "version": "1.0.0",
          "main": "server.mjs",
          "type": "module",
          "dependencies": {
            "axios": "^1.8.4",
            "jsonwebtoken": "^9.0.2",
            "rsa-pem-from-mod-exp": "^0.8.6"
          }
        }
      source: |
        import axios from "axios";
        import jwt from "jsonwebtoken";
        import getPem from "rsa-pem-from-mod-exp";

        const getJWTPublicKey = async () => {
          const response = await axios.get(
            "https://accounts.gigya.com/accounts.getJWTPublicKey",
            {
              params: { apiKey: process.env.CDC_API_KEY, V2: true },
            }
          );
          return response;
        };

        const verifyJWT = (sigJwt, nModulus, eExponent) => {
          try {
            const cert = getPem(nModulus, eExponent);
            const payload = jwt.verify(sigJwt, cert, { algorithms: ["RS256"] });
            console.log("Verified payload: ", JSON.stringify(payload));
            return true;
          } catch (err) {
            console.error("Error verifying JWT: ", err);
            return false;
          }
        };

        const processEvents = (events) => {
          console.log("Processing events: ", JSON.stringify(events));
        };

        export async function main(event, context) {
          const { CDC_N_MODULUS, CDC_E_EXPONENT, CDC_KID } = process.env;
          const res = event.extensions.response;

          if (!event) return res.status(400);

          const headers = event.extensions.request.headers;
          const sigJwt = headers["x-gigya-sig-jwt"];

          if (!sigJwt) return res.status(400);

          let nModulus = CDC_N_MODULUS;
          let eExponent = CDC_E_EXPONENT;

          const decoded = jwt.decode(sigJwt, { complete: true });

          if (CDC_KID !== decoded?.header?.kid) {
            try {
              const { data } = await getJWTPublicKey();
              if (data?.statusCode === 200) {
                const key = data.keys.find((key) => key.kid === CDC_KID);
                if (key) {
                  nModulus = key.n;
                  eExponent = key.e;
                }
              }
            } catch (err) {
              console.error("Error fetching JWT public key: ", err);
              return res.status(400);
            }
          }

          if (!verifyJWT(sigJwt, nModulus, eExponent)) {
            return res.status(400);
          }

          if (event.data?.events) {
            processEvents(event.data.events);
          }

          return res.status(200);
        }
